name: auto_LiRPA CI
on: [push]
jobs:
  Tests:
    runs-on: self-hosted
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install PyTorch
        run: pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
      - name: Install auto_LiRPA
        run: python setup.py install
      - name: Install dependencies for examples
        run: |
          pip install -r examples/requirements.txt
          pip install -r complete_verifier/requirements.txt
          cd ..
      - name: Run tests
        run: |
          cd tests
          python utils/download_models.py
          OMP_NUM_THREADS=1 pytest
